name: Executable workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  print:
    uses: darshini-dd/github-actions-templates/.github/workflows/print.yaml@feature/github-actions-migration
    with:
      environment: ${{ inputs.environment }}
      branch_name: ${{ inputs.branch_name}}