name: Executes workflow inputs
on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      branch_name:
        required: true
        type: string
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Branch name: ${{ inputs.branch_name }}"